/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import java.io.File;
import javax.swing.JOptionPane;
import jdk.nashorn.internal.codegen.CompilerConstants;
import messagepassing.Mailbox;
import messagepassing.Proceso;
import messagepassing.SingletonConfiguracion;
import messagepassing.TipoContenido;

/**
 *
 * @author Sebas
 */
public class Configuraciones extends javax.swing.JFrame {

    /**
     * Creates new form Configuraciones
     */
    public Configuraciones() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        sendBlocking = new javax.swing.JRadioButton();
        sendNonBlocking = new javax.swing.JRadioButton();
        jLabel3 = new javax.swing.JLabel();
        radioButtonBlocking = new javax.swing.JRadioButton();
        radioButtonNonBlocking = new javax.swing.JRadioButton();
        radioButtonllegada = new javax.swing.JRadioButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        RadioButtonExplicito = new javax.swing.JRadioButton();
        RadioButtonImplicito = new javax.swing.JRadioButton();
        jLabel8 = new javax.swing.JLabel();
        RadioButtonEstatitco = new javax.swing.JRadioButton();
        RadioButtonDinamico = new javax.swing.JRadioButton();
        jLabel9 = new javax.swing.JLabel();
        RadioButtonFIFO = new javax.swing.JRadioButton();
        jLabel10 = new javax.swing.JLabel();
        ComboBoxFormato = new javax.swing.JComboBox<>();
        TextField_tamaño = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        BotonNext = new javax.swing.JButton();
        RadioButtonPrioridad = new javax.swing.JRadioButton();
        jLabel12 = new javax.swing.JLabel();
        TexfieldProcesos = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Sincronización");

        jLabel2.setText("Send");

        sendBlocking.setText("Blocking");
        sendBlocking.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                sendBlockingStateChanged(evt);
            }
        });
        sendBlocking.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sendBlockingActionPerformed(evt);
            }
        });

        sendNonBlocking.setText("Non-blocking");
        sendNonBlocking.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                sendNonBlockingStateChanged(evt);
            }
        });
        sendNonBlocking.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sendNonBlockingActionPerformed(evt);
            }
        });

        jLabel3.setText("Recieve");

        radioButtonBlocking.setText("Blocking");
        radioButtonBlocking.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                radioButtonBlockingStateChanged(evt);
            }
        });

        radioButtonNonBlocking.setText("Non-blocking");
        radioButtonNonBlocking.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                radioButtonNonBlockingStateChanged(evt);
            }
        });

        radioButtonllegada.setText("Prueba de llegada");
        radioButtonllegada.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                radioButtonllegadaStateChanged(evt);
            }
        });

        jLabel4.setText("Direccionamiento");

        jLabel5.setText("Directo");

        jLabel6.setText("Send");

        jLabel7.setText("Receive");

        RadioButtonExplicito.setText("Explicito");
        RadioButtonExplicito.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                RadioButtonExplicitoStateChanged(evt);
            }
        });
        RadioButtonExplicito.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RadioButtonExplicitoActionPerformed(evt);
            }
        });

        RadioButtonImplicito.setText("Implicito");
        RadioButtonImplicito.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                RadioButtonImplicitoStateChanged(evt);
            }
        });
        RadioButtonImplicito.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RadioButtonImplicitoActionPerformed(evt);
            }
        });

        jLabel8.setText("Indirecto");

        RadioButtonEstatitco.setText("Estatico");
        RadioButtonEstatitco.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                RadioButtonEstatitcoStateChanged(evt);
            }
        });
        RadioButtonEstatitco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RadioButtonEstatitcoActionPerformed(evt);
            }
        });

        RadioButtonDinamico.setText("Dinamico");
        RadioButtonDinamico.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                RadioButtonDinamicoStateChanged(evt);
            }
        });
        RadioButtonDinamico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RadioButtonDinamicoActionPerformed(evt);
            }
        });

        jLabel9.setText("Disciplina de manejo de datos");

        RadioButtonFIFO.setText("FIFO");
        RadioButtonFIFO.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                RadioButtonFIFOStateChanged(evt);
            }
        });
        RadioButtonFIFO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RadioButtonFIFOActionPerformed(evt);
            }
        });

        jLabel10.setText("Formato");

        ComboBoxFormato.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Texto", "Audio", "Video", "Imagenes", " " }));
        ComboBoxFormato.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComboBoxFormatoActionPerformed(evt);
            }
        });

        jLabel11.setText("Tamaño");

        BotonNext.setText("Next");
        BotonNext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonNextActionPerformed(evt);
            }
        });

        RadioButtonPrioridad.setText("Priodidad");
        RadioButtonPrioridad.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                RadioButtonPrioridadStateChanged(evt);
            }
        });
        RadioButtonPrioridad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RadioButtonPrioridadActionPerformed(evt);
            }
        });

        jLabel12.setText("Procesos");

        jButton1.setText("Ayuda");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(66, 66, 66)
                        .addComponent(jLabel2)
                        .addGap(308, 308, 308)
                        .addComponent(jLabel5))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(85, 85, 85)
                        .addComponent(sendBlocking)
                        .addGap(289, 289, 289)
                        .addComponent(jLabel6))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(85, 85, 85)
                        .addComponent(sendNonBlocking)
                        .addGap(265, 265, 265)
                        .addComponent(jLabel7))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(66, 66, 66)
                        .addComponent(jLabel3)
                        .addGap(358, 358, 358)
                        .addComponent(RadioButtonExplicito))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(87, 87, 87)
                        .addComponent(radioButtonNonBlocking)
                        .addGap(226, 226, 226)
                        .addComponent(jLabel8))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(87, 87, 87)
                        .addComponent(radioButtonllegada)
                        .addGap(242, 242, 242)
                        .addComponent(RadioButtonEstatitco))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(jLabel10)
                        .addGap(370, 370, 370)
                        .addComponent(RadioButtonDinamico))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(83, 83, 83)
                        .addComponent(TextField_tamaño, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel9)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel11)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(ComboBoxFormato, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(268, 268, 268)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(RadioButtonFIFO)
                                    .addComponent(RadioButtonPrioridad)))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGap(41, 41, 41)
                                .addComponent(TexfieldProcesos, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(87, 87, 87)
                                .addComponent(radioButtonBlocking)
                                .addGap(312, 312, 312)
                                .addComponent(RadioButtonImplicito)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(BotonNext, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(44, 44, 44))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel12)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel1)
                .addGap(261, 261, 261)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(22, 22, 22))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel4)
                        .addComponent(jButton1)))
                .addGap(1, 1, 1)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel5))
                .addGap(2, 2, 2)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(sendBlocking)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(jLabel6)))
                .addGap(3, 3, 3)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(sendNonBlocking)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(jLabel7)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(jLabel3))
                    .addComponent(RadioButtonExplicito))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(radioButtonBlocking)
                    .addComponent(RadioButtonImplicito))
                .addGap(3, 3, 3)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(radioButtonNonBlocking)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(jLabel8)))
                .addGap(1, 1, 1)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(radioButtonllegada))
                    .addComponent(RadioButtonEstatitco))
                .addGap(5, 5, 5)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jLabel10))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(RadioButtonDinamico)
                        .addGap(7, 7, 7)
                        .addComponent(jLabel9)))
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(ComboBoxFormato, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(13, 13, 13)
                        .addComponent(jLabel11))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(RadioButtonFIFO)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addComponent(RadioButtonPrioridad)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TextField_tamaño, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(49, 49, 49)
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TexfieldProcesos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BotonNext))
                .addContainerGap(13, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void sendBlockingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sendBlockingActionPerformed

    }//GEN-LAST:event_sendBlockingActionPerformed

    private void sendNonBlockingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sendNonBlockingActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sendNonBlockingActionPerformed

    private void RadioButtonExplicitoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RadioButtonExplicitoActionPerformed
        
        if(this.RadioButtonExplicito.isSelected()){   
        this.RadioButtonEstatitco.setEnabled(false);
        
        }
        else
        this.RadioButtonEstatitco.setEnabled(true);
        
        if(this.RadioButtonExplicito.isSelected()){   
        this.RadioButtonDinamico.setEnabled(false);
        }
        else
        this.RadioButtonDinamico.setEnabled(true);
    }//GEN-LAST:event_RadioButtonExplicitoActionPerformed

    private void BotonNextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonNextActionPerformed
        boolean b1=false;
        boolean b2=false;
        boolean b3=false;
        boolean b4=false;
        boolean b5=false;
        boolean b6=false;
        if (this.sendBlocking.isSelected() || this.sendNonBlocking.isSelected()) {
            b1=true;
            if (this.sendBlocking.isSelected()) {
                SingletonConfiguracion.sendBlocking = true;
                SingletonConfiguracion.sendNonBlocking = false;
            } else {
                SingletonConfiguracion.sendBlocking = false;
                SingletonConfiguracion.sendNonBlocking = true;
            }
            
        } 
        //------------------------------------------------------------------------------------------------------------------------
        if (this.radioButtonBlocking.isSelected() || this.radioButtonNonBlocking.isSelected() || this.radioButtonllegada.isSelected()) {
            b2=true;
            if (this.radioButtonBlocking.isSelected()) {
                SingletonConfiguracion.recieveBlocking = true;
                SingletonConfiguracion.recieveNonBlocking = false;
                SingletonConfiguracion.recieveLlegada = false;
            } else if (this.radioButtonNonBlocking.isSelected()) {
                SingletonConfiguracion.recieveBlocking = false;
                SingletonConfiguracion.recieveNonBlocking = true;
                SingletonConfiguracion.recieveLlegada = false;
            } else {
                SingletonConfiguracion.recieveBlocking = false;
                SingletonConfiguracion.recieveNonBlocking = false;
                SingletonConfiguracion.recieveLlegada = true;

            }
        } 
        //----------------------------------------------------------------------------------------------------------------------------
        if (this.ComboBoxFormato.getSelectedItem().equals("Texto")) {
            
            SingletonConfiguracion.Formato = TipoContenido.valueOf("Texto");

        } else if (this.ComboBoxFormato.getSelectedItem().equals("Audio")) {
            SingletonConfiguracion.Formato = TipoContenido.valueOf("Audio");
        } else if (this.ComboBoxFormato.getSelectedItem().equals("Video")) {
            SingletonConfiguracion.Formato = TipoContenido.valueOf("Video");
        } else {
            SingletonConfiguracion.Formato = TipoContenido.valueOf("Imagen");
        }
        //-------------------------------------------------------------------------------------------------------------------------

        if (this.TextField_tamaño.getText().isEmpty()) {
            SingletonConfiguracion.tamañoLimite = 0;
        } else {
            SingletonConfiguracion.tamañoLimite = Integer.parseInt(this.TextField_tamaño.getText().toString());// ver si funciona
        }
//---------------------------------------------------------------------------------------------

        if (this.RadioButtonExplicito.isSelected() || this.RadioButtonImplicito.isSelected()) {
            b3=true;
            SingletonConfiguracion.direccionamientoDirecto=true;
            this.RadioButtonEstatitco.setEnabled(false);
            this.RadioButtonDinamico.setEnabled(false);
            
            if (this.RadioButtonExplicito.isSelected()) {
                SingletonConfiguracion.directoRecieveExplicito = true;
                SingletonConfiguracion.directoRecieveImplicito = false;
            } else {
                SingletonConfiguracion.directoRecieveExplicito = false;
                SingletonConfiguracion.directoRecieveImplicito = true;
            }
        } 
//--------------------------------------------------------------------------------------------

        if (this.RadioButtonEstatitco.isSelected() || this.RadioButtonDinamico.isSelected()) {
            b4=true;
             SingletonConfiguracion.direccionamientoDirecto=false;
            this.RadioButtonExplicito.setEnabled(false);
            this.RadioButtonImplicito.setEnabled(false);
            
            //Crear el mailbox general?
            
            if (this.RadioButtonEstatitco.isSelected()) {
                SingletonConfiguracion.indirectoEstatico = true;
                SingletonConfiguracion.indirectoDinamico = false;
                
            } else {
                SingletonConfiguracion.indirectoEstatico = false;
                SingletonConfiguracion.indirectoDinamico = true;
            }
        } 
//---------------------------------------------------------------------------------------------
        if (this.RadioButtonFIFO.isSelected() || this.RadioButtonPrioridad.isSelected()) {
            b5=true;
            if (this.RadioButtonFIFO.isSelected()) {
                SingletonConfiguracion.FIFO = true;
                SingletonConfiguracion.prioridad = false;
            } else {
                SingletonConfiguracion.FIFO = false;
                SingletonConfiguracion.prioridad = true;
            }
        } 
//----------------------------------------------------------------------------------------------------
        if (this.TexfieldProcesos.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Se debe de poner la cantidad de procesos");
            return;
        } else {
            b6=true;
            if (Integer.parseInt(this.TexfieldProcesos.getText().toString()) >= 2) {
                SingletonConfiguracion.cantidadProcesos = Integer.parseInt(this.TexfieldProcesos.getText().toString());// ver si funciona
                
            } else {
                JOptionPane.showMessageDialog(null, "La cantidad de procesos debe de ser mayor a 2");
            }
        }

// si llegó aqui entonces todo bien
// la oculto para tener la posibilidad de volver a la pantalla anterior y tener todo seleccionado como estaba, si se usa dispose se destruye todo
if(b1==true && b2==true &&( b3==true || b4==true) && b5==true && b6==true){        
for (int i = 0; i < SingletonConfiguracion.cantidadProcesos+2; i++) {
            int num=i;
            String cont= Integer.toString(num);
            Proceso temp= new Proceso(null, "p"+cont, new Mailbox("p"+cont), new Mailbox("p"+cont));
            if(SingletonConfiguracion.indirectoDinamico==true){
                 temp.setSuscrito(true);
                 SingletonConfiguracion.ListaDeProcesos.add(temp);
            }
            else{
                SingletonConfiguracion.ListaDeProcesos.add(temp);
            }
           
            
        }
Interactivo ventana = new Interactivo();
                ventana.setVisible(true);
                this.setVisible(false);
    }
else{
    JOptionPane.showMessageDialog(null, "Debes de completar todos los campos");
}
            
        
        for ( int a=0; a<SingletonConfiguracion.ListaDeProcesos.size();a++){
            System.out.println(SingletonConfiguracion.ListaDeProcesos.get(a).getIdentificadorProceso());
        }
        
// TODO add your handling code here:
    }//GEN-LAST:event_BotonNextActionPerformed

    private void RadioButtonDinamicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RadioButtonDinamicoActionPerformed
        
         if(this.RadioButtonDinamico.isSelected()){   
        this.RadioButtonExplicito.setEnabled(false);
        
        }
        else
        this.RadioButtonExplicito.setEnabled(true);
        
        if(this.RadioButtonDinamico.isSelected()){   
        this.RadioButtonImplicito.setEnabled(false);
        }
        else
        this.RadioButtonImplicito.setEnabled(true);
    }//GEN-LAST:event_RadioButtonDinamicoActionPerformed

    private void sendBlockingStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_sendBlockingStateChanged
        if (this.sendBlocking.isSelected()) {
            this.sendNonBlocking.setSelected(false);// TODO add your handling code here:
        }                 // TODO add your handling code here:
    }//GEN-LAST:event_sendBlockingStateChanged

    private void sendNonBlockingStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_sendNonBlockingStateChanged
        if (this.sendNonBlocking.isSelected()) {
            this.sendBlocking.setSelected(false);// TODO add your handling code here:
        }             // TODO add your handling code here:
    }//GEN-LAST:event_sendNonBlockingStateChanged

    private void radioButtonBlockingStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_radioButtonBlockingStateChanged
        if (this.radioButtonBlocking.isSelected()) {
            this.radioButtonNonBlocking.setSelected(false);
            this.radioButtonllegada.setSelected(false);
        }        // TODO add your handling code here:
    }//GEN-LAST:event_radioButtonBlockingStateChanged

    private void radioButtonNonBlockingStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_radioButtonNonBlockingStateChanged
        if (this.radioButtonNonBlocking.isSelected()) {
            this.radioButtonBlocking.setSelected(false);
            this.radioButtonllegada.setSelected(false);
        }   // TODO add your handling code here:
    }//GEN-LAST:event_radioButtonNonBlockingStateChanged

    private void radioButtonllegadaStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_radioButtonllegadaStateChanged
        if (this.radioButtonllegada.isSelected()) {
            this.radioButtonBlocking.setSelected(false);
            this.radioButtonNonBlocking.setSelected(false);
        }  // TODO add your handling code here:
    }//GEN-LAST:event_radioButtonllegadaStateChanged

    private void RadioButtonImplicitoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RadioButtonImplicitoActionPerformed
        
        if(this.RadioButtonImplicito.isSelected()){   
        this.RadioButtonEstatitco.setEnabled(false);
        
        }
        else
        this.RadioButtonEstatitco.setEnabled(true);
        
        if(this.RadioButtonImplicito.isSelected()){   
        this.RadioButtonDinamico.setEnabled(false);
        }
        else
        this.RadioButtonDinamico.setEnabled(true);
    }//GEN-LAST:event_RadioButtonImplicitoActionPerformed

    private void RadioButtonFIFOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RadioButtonFIFOActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RadioButtonFIFOActionPerformed

    private void RadioButtonPrioridadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RadioButtonPrioridadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RadioButtonPrioridadActionPerformed

    private void RadioButtonPrioridadStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_RadioButtonPrioridadStateChanged
        if (this.RadioButtonPrioridad.isSelected()) {
            this.RadioButtonFIFO.setSelected(false);
        } // T        
        // TODO add your handling code here:
    }//GEN-LAST:event_RadioButtonPrioridadStateChanged

    private void RadioButtonExplicitoStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_RadioButtonExplicitoStateChanged
        if (this.RadioButtonExplicito.isSelected()) {
            this.RadioButtonImplicito.setSelected(false);
        }        // TODO add your handling code here:
    }//GEN-LAST:event_RadioButtonExplicitoStateChanged

    private void RadioButtonImplicitoStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_RadioButtonImplicitoStateChanged
        if (this.RadioButtonImplicito.isSelected()) {
            this.RadioButtonExplicito.setSelected(false);
        } // TODO add your handling code here:
    }//GEN-LAST:event_RadioButtonImplicitoStateChanged

    private void RadioButtonEstatitcoStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_RadioButtonEstatitcoStateChanged
        if (this.RadioButtonEstatitco.isSelected()) {
            this.RadioButtonDinamico.setSelected(false);
        } // TODO add your handling code here:
    }//GEN-LAST:event_RadioButtonEstatitcoStateChanged

    private void RadioButtonDinamicoStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_RadioButtonDinamicoStateChanged
        if (this.RadioButtonDinamico.isSelected()) {
            this.RadioButtonEstatitco.setSelected(false);
        } // TODO  // TODO add your handling code here:
    }//GEN-LAST:event_RadioButtonDinamicoStateChanged

    private void RadioButtonFIFOStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_RadioButtonFIFOStateChanged
        if (this.RadioButtonFIFO.isSelected()) {
            this.RadioButtonPrioridad.setSelected(false);
        } // T        
// TODO add your handling code here:
    }//GEN-LAST:event_RadioButtonFIFOStateChanged

    private void ComboBoxFormatoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComboBoxFormatoActionPerformed
       
        
    }//GEN-LAST:event_ComboBoxFormatoActionPerformed

    private void RadioButtonEstatitcoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RadioButtonEstatitcoActionPerformed
        
        if(this.RadioButtonEstatitco.isSelected()){   
        this.RadioButtonExplicito.setEnabled(false);
        
        }
        else
        this.RadioButtonExplicito.setEnabled(true);
        
        if(this.RadioButtonEstatitco.isSelected()){   
        this.RadioButtonImplicito.setEnabled(false);
        }
        else
        this.RadioButtonImplicito.setEnabled(true);
    }//GEN-LAST:event_RadioButtonEstatitcoActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed


	  try {

		if ((new File("Documentacion.pdf")).exists()) {

			Process p = Runtime
			   .getRuntime()
			   .exec("rundll32 url.dll,FileProtocolHandler Documentacion.pdf");
			p.waitFor();
				
		} else {

			System.out.println("File is not exists");

		}

		System.out.println("Done");

  	  } catch (Exception ex) {
		ex.printStackTrace();
	  }



        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Configuraciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Configuraciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Configuraciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Configuraciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Configuraciones().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotonNext;
    private javax.swing.JComboBox<String> ComboBoxFormato;
    private javax.swing.JRadioButton RadioButtonDinamico;
    private javax.swing.JRadioButton RadioButtonEstatitco;
    private javax.swing.JRadioButton RadioButtonExplicito;
    private javax.swing.JRadioButton RadioButtonFIFO;
    private javax.swing.JRadioButton RadioButtonImplicito;
    private javax.swing.JRadioButton RadioButtonPrioridad;
    private javax.swing.JTextField TexfieldProcesos;
    private javax.swing.JTextField TextField_tamaño;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JRadioButton radioButtonBlocking;
    private javax.swing.JRadioButton radioButtonNonBlocking;
    private javax.swing.JRadioButton radioButtonllegada;
    private javax.swing.JRadioButton sendBlocking;
    private javax.swing.JRadioButton sendNonBlocking;
    // End of variables declaration//GEN-END:variables
}
